baseURL = "https://localhost:1313"
languageCode = "en-us"
title = "Mediumish"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "John Doe - All rights reserved"
enableEmoji = true
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/logo.png"
  description ="the clean blog!"

[params.author]
  name = "John Doe"
  thumbnail = "/images/author.png"
  description = "Creator of this blog."

[params.index]
  picture = "/images/author.png"
  title = "John Doe"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''
Seeking ~~knowledge and~~ money. Currently trying to get this blog running, still don't know what the blog will be about!
'''
  alertbar = false

[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/"
[[menu.main]]
    name = "Imprint"
    identifier = "imprint"
    weight = 200
    url = "/static/imprint"
